spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.hpu.entities
  mapper‐locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  application:
    name: microservicecloud-provider-dept   # 为这个服务取名，非常重要！！！！！
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false    # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                        # 数据库连接池的最小维持连接数
      initial-size: 5                                    # 初始化连接数
      max-total: 5                                       # 最大连接数
      max-wait-millis: 200                               # 等待连接获取的最大超时时间

eureka:
  client:
    service‐url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance‐id: config-dept8001
    prefer‐ip‐address: true

---

server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.hpu.entities
  mapper‐locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  profiles: test
  application:
    name: microservicecloud-provider-dept   # 为这个服务取名，非常重要！！！！！
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false    # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                        # 数据库连接池的最小维持连接数
      initial-size: 5                                    # 初始化连接数
      max-total: 5                                       # 最大连接数
      max-wait-millis: 200                               # 等待连接获取的最大超时时间

eureka:
  client:
    service‐url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance‐id: config-dept8001
    prefer‐ip‐address: true